import { nanoid } from 'nanoid';

const date = new Date();
const year = date.getFullYear();
const month = (date.getMonth() + 1).toString().padStart(2, '0');
const day = date.getDate().toString().padStart(2, '0');

export const currentDate = `${year}-${month}-${day}`;

export const defaultGroups = [
  {
    name: '🎨 Crafters',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '📚 Book Worms',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '⚽️ Footballers',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '🎵 Music Lovers',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '🌿 Green Thumbs',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '🍳 Foodies',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '🎮 Game Warriors',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '🏋️  Fitness Warriors',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '🎥 Popcorn Munchers',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '🐶 Dogs Lovers',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '🐈 Cats Lovers',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '🚴 Cycling Fanatics',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '🧘 Zen Seekers',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '📸 Shutterbugs',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '🎲 Boardgame Guild',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '🤝 Social Butterflies',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '🏞️ Outdoor Explorers',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
  {
    name: '💃 Rhythm Rebels',
    adminId: 'default',
    id: nanoid(),
    members: [],
    allPosts: [],
    description: '',
  },
];
